### ISSUE TITLE
JLoader::_autoload problem with registration prefixes with first letters J

### ISSUE THREAD

**Issue by GerrAlt12** [joomla/joomla-platform#1628] opened 2012-10-22 13:06 UTC
Hello!

I creating my component for Joomla, and i select prefix for my classes "Jmc".

After I register this prefix by JLoader::registerPrefix autoloading of classes still not working.

I think problem in line 299 in /libraries/loader.php

"if (strpos($class, $prefix) === 0)"

Class name "JmcController", this criteria is TRUE for prefix "Jmc" and for prefix "J", but "J" is first in massive.

Maybe it is not a bug, but some extension may conflict, if one have prefix for classes "Abc", and another has prefix "Abczzz"

Maybe more complex criteria is better?

**Comment by Skullbock** [comment] 2012-10-22 13:07
I solved this in my app inverting the registration of prefixes

JLoader::registerPrefix('Jcm', './jcm/');
JLoader::setup();

This works, since it's a FIFO queue

Daniele Rosario

**Comment by GerrAlt12** [comment] 2012-10-22 13:14
My code in component core php file:

JLoader::registerPrefix('Jmc', underscore underscore DIR underscore underscore );
JLoader::setup();

Autoloading still not working.
I do something wrong?

**Comment by Skullbock** [comment] 2012-10-22 13:22
I think it's the CamelCase syntax. Since you have JcmClass, it searches the
prefix J.
Try using JCMClass and see if that works

Daniele Rosario

**Comment by GerrAlt12** [comment] 2012-10-22 19:15
I reneme all my classes, and change syntax like this:

JLoader::registerPrefix('JMC', underscore underscore DIR underscore underscore );
JLoader::setup();

Nothing changes

**Comment by Skullbock** [comment] 2012-10-23 07:44
Strange, in my project i'm doing it like this:

// Setup the autoloaders.
JLoader::registerPrefix('JC', './jc/');
JLoader::setup();

And it works like a charm
Which version of the platform are you on? And which error does it trigger?

Daniele Rosario

**Comment by GerrAlt12** [comment] 2012-10-23 08:45
OK
I'm found mistake

When I use registrPrefix with "Jmc", and trying to load class with name JmcController, autoloader search file "controller.php" in subfolder "controller", not in base path.

It's strictly like it is discribed in manual, it's not a bug :)

I use platform 12.1

**Comment by Skullbock** [comment] 2012-10-23 08:50
Yes, that's definetly the issue.

If you want to load a JcmController class, use the

JLoader::registerPrefix('Jmc', './');
JLoader::setup();

and a folder structure like

/controller/controller.php

Daniele Rosario

**Comment by GerrAlt12** [comment] 2012-10-23 09:28
JLoader::setup(); maybe not necessary, without this line all works fine

**Comment by pasamio** [comment] 2012-10-23 15:41
As pointed out by the reporter, this is the expected behaviour. Closing issue.

**Closed as completed by pasamio** 2012-10-23 15:41 UTC
Labels: Issue fixed
