### ISSUE TITLE
JFactory::getApplication($id) return the same object for site and admin

### ISSUE THREAD

**Issue by tbela99** [joomla/joomla-platform#987] opened 2012-03-15 12:51 UTC
JFactory::getApplication($id) return the same object no matter the value of $id (site or admin)

it always return JFactory::$application property.

**Comment by elinw** [comment] 2012-04-09 09:48
Has this been addressed by JApplicationBase?

**Comment by AmyStephen** [comment] 2012-04-09 13:11
Are you sending in "admin" - or "administrator"?

**Comment by tbela99** [comment] 2012-04-09 13:36
look at the source code here https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/factory.php#L94
once you call JFactory::getApplication(), the result is saved. and no matter which parameter you pass, 
JFactory::getApplication('site') and JFactory::getApplication('administrator') will return the same object

**Comment by AmyStephen** [comment] 2012-04-09 13:58
@tbela99 - Ok, I see what you are asking. In Joomla, there is only one application that runs at a time, so, that would be expected behavior. The application is a static instance.

**Comment by tbela99** [comment] 2012-04-09 16:44
in this case you should remove the parameter

**Comment by tbela99** [comment] 2012-04-09 16:47
in this case you should remove the parameter. it makes no sense to have a parameter if you are true.
an example where I need the other behavior is that I want to get the site router from the backend, I expected JFactory::getInstance('site')->getRouter() to return a site router, but it is not possible from the backend

**Comment by AmyStephen** [comment] 2012-04-09 17:16
@tbela99 - if you removed the parameter, how would be able to determine which application has been requested?

Don't use JFactory if you want to create a new instance of another application. The intention and purpose of JFactory is to provide static (one time) instances of objects that are only to be created one time per page load. If you need something else (like figuring out something for another application that isn't current), don't use JFactory. Just create the instance yourself.

$otherApp = JApplication::getInstance('site');
$router = $otherApp->getRouter(); 

etc.

Would that work? (Actually, not even sure you can do that given paths, etc., but that would be worth a try.)

**Comment by tbela99** [comment] 2012-04-09 17:27
if there is a parameter then: 
if I call JFactory::getApplication('site') I must expect a JApplicationSite instance,
the same way JFactory::getApplication('administrator') I must expect a JApplicationAdministrator instance.

otherwise there is an error in your logic

**Comment by tbela99** [comment] 2012-04-09 17:29
the current behavior is:

//from the front end
 JFactory::getApplication('site') -> JApplicationSite
 JFactory::getApplication('administrator') -> JApplicationSite

//from the back end
 JFactory::getApplication('site') -> JApplicationAdministrator
 JFactory::getApplication('administrator') -> JApplicationAdministrator

**Comment by tbela99** [comment] 2012-04-09 17:30
either you remove the parameter and the method return the right JApplication instance or you return the instance that correspond to the given parameter

**Comment by AmyStephen** [comment] 2012-04-09 18:11
@tbela99 - 

We are going in circles, here. This isn't my code and I am not defending it, just explaining it. 

For better or worse, the purpose of JFactory is to create an instance of various application objects ONE TIME - and then store that instance as a static object, making it available for later calls within the application.

So, the first time the application invokes JFactory::getApplication('site') - it needs the parameter. From that point on, JFactory  returns whatever application object it stored in the static variable. 

That's how JFactory is intended to work, for better or worse. In fact, many times, you'll not see the application name in the JFactory::getApplication() call because it's known that the current application will be returned. 

I understand your point that sending in a parameter should return an object that corresponds to that parameter value -- but, it's always wise to review the code to see what really happens.  

Try my suggestion above (don't get the application object from JFactory) -- see if that works. I don't know that it will since it's possible paths and other constants won't be established properly. I've never had any reason to use multiple applications at once so probably can't help more.

But, this is not a bug, it's just how JFactory works. (I do understand it's not how you'd like to see JFactory work and I get your point -- but it doesn't change the fact that it _is_ how works, nonetheless.)

G luck.

**Comment by tbela99** [comment] 2012-04-10 08:36
I know how to get around this issue, my problem is about the behavior of this method. it needs to be fixed

**Comment by AmyStephen** [comment] 2012-04-10 13:33
JFactory is not broken. It works exactly as it's intended to work.

**Comment by tbela99** [comment] 2012-04-10 14:50
this behavior is misleading and should be changed. when I pass a parameter, I expect the right result otherwise or  I wont have to pass a parameter and:
when I call it from the front end I'll got a JApplicationSite
when I call it from the back end I'll have a JApplicationAdminsitrator

the behavior should be one between what I have mentioned

**Comment by AmyStephen** [comment] 2012-04-10 15:06
Well, you can do a PR and see if the platform team accepts it. I don't control that so maybe they'll agree. 

Hope my explanation helped. Going to disable notifications since I have nothing else to offer. 

Good luck.

**Comment by danyj** [comment] 2012-09-26 23:33
I just ran in to same issue tbela99 , 

I actually want to know from admin backend what template is set as default in frontend and thought that Japp or Jfactory would tell me this , but to my surprise , it gives me only admin  side instance info instead frontend 

$getinfo = JFactory::getApplication('site');

if  print_r in admin I would expect to tell me what is in frontend.

 tried Amy's suggestion but it is same 
$getinfo = JApplication::getInstance('site');

**Comment by elinw** [comment] 2012-09-27 03:36
I think the parameter just lets you give the current instance of an application a  name, it's not that you can go creating instances of other applications.   In the CMS we sometimes use the names to basically answer the question "where are we?" so that we can decide things like whether to run a system plugin (which we might run only when the name of the application is site). 

 if the application is not running in the current instance how does JApplication even know where to get the information? If you look at say
https://github.com/joomla/joomla-platform-examples/tree/master/web/detect-client
and
https://github.com/joomla/joomla-platform-examples/tree/master/web/flickr-feed
Say from inside detect-client you went to find out what default template flickr-feed was using?  You could but you would probably most easily do it by maybe reading where that information is stored, not by creating an instance of the application.

If you want to know the default template of the site application of the cms I would honestly just get that from #__template_styles.

**Comment by danyj** [comment] 2012-09-27 03:40
Thnx Elin , I did end up looking at the DB , but first tough was that site instance would give me the info. Thnx for explaining.

**Comment by mahagr** [comment] 2012-09-29 06:12
As part of this issue, one use case I've trying to find out is how to use JRoute for the site from the backend. Or how to get site menu structure and find out the right Itemid in a logical and standard way.

**Comment by elinw** [comment] 2012-09-29 17:32
I do think moving forward we need to have easy ways for applications to share information and the platform should support that but some of that  may need to come from the application too or from plugins. But I haven't really thought that through at all.

**Comment by dongilbert** [comment] 2013-03-16 04:41
JApplication has been moved the legacy tree. The bug reported here has been fixed in the new MVC and Application base classes. Closing this.

**Closed as completed by dongilbert** 2013-03-16 04:41 UTC
