### ISSUE TITLE
Sessions don't work well with other than database handler.

### ISSUE THREAD

**Issue by elpescador** [joomla/joomla-platform#360] opened 2011-09-13 22:23 UTC
I found out this issue and it might be related to this one @ joomlacode.org as well...

What I can see is that I somehow are logged on to the administrator and have no modules at all, so no menu and toolbar. Navigation is impossible.

Can you reproduce/confirm this issue?

Is it related to this problem in Joomlacode.org? http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=25069

**Comment by elinw** [comment] 2012-05-14 23:25
I'm not sure what this has to do with sessions. You are getting that symptom because you logged in as a member of a user group that does not have permission to see "special" items.

**Comment by LouisLandry** [comment] 2012-10-09 00:11
I'm going to close this since we don't have good information on it.  In the future please add more information on what the problem is so that we can diagnose.

**Closed as completed by LouisLandry** 2012-10-09 00:11 UTC
