### ISSUE TITLE
TableNested Publish Return Error

### ISSUE THREAD

**Issue by davidhurley** [joomla/joomla-platform#706] opened 2012-01-05 03:28 UTC
Noticed a bug in base file tablenested.php

Line 884 public function publish(...

Returns a boolean True on success. However, it seems that it should instead return a number of affected rows. The modeladmin.php file line 865 seems to expect a count integer as a response because it then returns that affected rows to the controlleradmin.php line 183.

Controlleradmin.php uses $cidsAffected to determine the number to display in the JText::plural system message.

As a result the system message on the admin side always returns a "1"

e.g. "1 categories successfully deleted / trashed / published" regardless of the actual number of $cids affected.

Not sure yet on the fastest and best way to fix this. I'm trying a couple of different things.

**Comment by elinw** [comment] 2012-01-05 23:59
David,

There has  been a huge ongoing discussion of this in JBS, would you want to join in on the discussion of solutions there? Then we can make one proposal that makes sense maybe.
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=27499

http://groups.google.com/group/joomlabugsquad/browse_thread/thread/65bb9489b91b10ae?pli=1

**Comment by davidhurley** [comment] 2012-01-06 00:03
Thanks Elin. I will do that!

**Comment by oc666** [comment] 2012-01-07 12:00
Hey David
This bug produce due to change in the publish action and it was started from this scenario bug: 
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=27257
The fix of this was not full implemented to the platform and the CMS, so another bug was opened (27499 as Elin mentioned). Meanwhile, Elin opened discussion (also mentioned in Elin comment) what is the correct behavior with different types of state changes (publish, unpublish, archive, etc) and what happened when item with sub-items change state.
Hope this is clarify the situation. 
Currently I've made a patch to fix all of those issues (see in bug tracker #27499)

**Comment by eddieajau** [comment] 2012-10-09 01:20
Closing as it sound like the CMS dealt with this. Reopen or resubmit if the issue persists.

**Closed as completed by eddieajau** 2012-10-09 01:20 UTC

**Comment by elinw** [comment] 2012-10-09 03:37
@eddieajau  we never got a reply to our post to the platform list about what the expected behavior is.  So no it has not been dealt with.  It would be awesome if one of you would reply to that email.
https://groups.google.com/d/topic/joomla-dev-platform/a0QirzNDaxI/discussion
